-- Run once in Supabase SQL Editor after schema.sql.
alter table public.posts add column if not exists is_removed boolean not null default false;

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (reason in ('spam', 'harassment', 'misinformation', 'copyright', 'other')),
  details text,
  status text not null default 'open' check (status in ('open', 'dismissed', 'actioned')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create index if not exists reports_status_created_at_idx on public.reports (status, created_at desc);
create index if not exists reports_post_id_idx on public.reports (post_id);
alter table public.reports enable row level security;
