-- TugasKu — complete schema for a NEW Supabase project
-- Run once in Supabase Dashboard → SQL Editor.
-- This script is idempotent for a fresh database. It does not delete existing data.

create extension if not exists pgcrypto;

-- User profiles (created by the app after Google OAuth sign-in)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  username text not null unique check (char_length(username) between 3 and 24),
  nickname text not null,
  bio text,
  avatar_url text,
  school text,
  education_level text,
  class_level text,
  favorite_subjects text[] not null default '{}',
  social_links jsonb not null default '{}'::jsonb,
  role text not null default 'user' check (role in ('user', 'owner')),
  created_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('question', 'answer')),
  title text not null check (char_length(title) between 5 and 160),
  content text not null check (char_length(content) between 10 and 20000),
  slug text not null unique,
  subject text not null,
  education_level text not null,
  class_level text not null,
  tags text[] not null default '{}',
  images text[] not null default '{}',
  like_count integer not null default 0 check (like_count >= 0),
  comment_count integer not null default 0 check (comment_count >= 0),
  bookmark_count integer not null default 0 check (bookmark_count >= 0),
  answer_count integer not null default 0 check (answer_count >= 0),
  view_count integer not null default 0 check (view_count >= 0),
  is_removed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.question_answers (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(content) between 5 and 20000),
  images text[] not null default '{}',
  upvote_count integer not null default 0 check (upvote_count >= 0),
  downvote_count integer not null default 0 check (downvote_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  parent_id bigint references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 2000),
  like_count integer not null default 0 check (like_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create table if not exists public.comment_likes (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (comment_id, user_id)
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  answer_id bigint not null references public.question_answers(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  value smallint not null check (value in (-1, 1)),
  created_at timestamptz not null default now(),
  unique (answer_id, user_id)
);

create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (reason in ('spam', 'harassment', 'misinformation', 'copyright', 'other')),
  details text,
  status text not null default 'open' check (status in ('open', 'dismissed', 'actioned')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  type text not null,
  entity_type text,
  entity_id bigint,
  post_slug text,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  category text not null check (category in ('bug', 'idea', 'other')),
  message text not null check (char_length(message) between 10 and 1200),
  created_at timestamptz not null default now()
);

-- Indexes used by feeds, profiles, notifications, and admin inbox.
create index if not exists posts_created_at_idx on public.posts (created_at desc);
create index if not exists posts_user_id_idx on public.posts (user_id, created_at desc);
create index if not exists posts_subject_idx on public.posts (subject);
create index if not exists posts_tags_idx on public.posts using gin (tags);
create index if not exists question_answers_post_id_idx on public.question_answers (post_id, created_at asc);
create index if not exists comments_post_id_idx on public.comments (post_id, created_at asc);
create index if not exists comments_parent_id_idx on public.comments (parent_id);
create index if not exists reports_status_created_at_idx on public.reports (status, created_at desc);
create index if not exists notifications_user_id_idx on public.notifications (user_id, is_read, created_at desc);
create index if not exists bookmarks_user_id_idx on public.bookmarks (user_id, created_at desc);
create index if not exists feedback_created_at_idx on public.feedback (created_at desc);
create index if not exists feedback_user_id_idx on public.feedback (user_id);

-- The Vercel API accesses data with SUPABASE_SERVICE_ROLE_KEY.
-- RLS remains enabled so the anon key cannot read/write tables directly.
alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.posts enable row level security;
alter table public.question_answers enable row level security;
alter table public.comments enable row level security;
alter table public.post_likes enable row level security;
alter table public.comment_likes enable row level security;
alter table public.votes enable row level security;
alter table public.bookmarks enable row level security;
alter table public.reports enable row level security;
alter table public.notifications enable row level security;
alter table public.feedback enable row level security;

-- Public bucket used by POST /api/upload. Service-role uploads bypass RLS.
insert into storage.buckets (id, name, public)
values ('tugasku-images', 'tugasku-images', true)
on conflict (id) do update set public = true;

-- Initial subjects (safe to run repeatedly)
insert into public.subjects (name, slug) values
  ('Matematika', 'matematika'),
  ('Bahasa Indonesia', 'bahasa-indonesia'),
  ('Bahasa Inggris', 'bahasa-inggris'),
  ('Fisika', 'fisika'),
  ('Kimia', 'kimia'),
  ('Biologi', 'biologi'),
  ('Sejarah', 'sejarah'),
  ('Geografi', 'geografi'),
  ('Ekonomi', 'ekonomi'),
  ('Informatika', 'informatika')
on conflict (slug) do nothing;
