-- Run once in Supabase SQL Editor for user reporting.
create table if not exists public.user_reports (
  id bigint generated by default as identity primary key,
  reported_user_id uuid not null references auth.users(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (reason in ('impersonation', 'harassment', 'spam', 'other')),
  details text,
  status text not null default 'open' check (status in ('open', 'dismissed', 'actioned')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (reported_user_id, user_id)
);
create index if not exists user_reports_status_created_at_idx on public.user_reports (status, created_at desc);
alter table public.user_reports enable row level security;
